language: python
env:
  global:
  - PROJECT_NAME=activitystreams
  - GITHUB_REPO_NAME=sovaa/activitystreams
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install codecov nose2
script:
  - nose2 --with-coverage -s test/
after_success:
  - codecov
